import 'package:equation_solver_mobile/core/localization/app_text_key.dart';

class SupportedLanguageOption {
  const SupportedLanguageOption({
    required this.code,
    required this.title,
    required this.subtitle,
  });

  final String code;
  final String title;
  final String subtitle;
}

class AppStringsCatalog {
  const AppStringsCatalog();

  static const fallbackLanguageCode = 'pt';

  static const supportedLanguageOptions = <SupportedLanguageOption>[
    SupportedLanguageOption(
      code: 'pt',
      title: 'Português',
      subtitle: 'Português',
    ),
    SupportedLanguageOption(code: 'de', title: 'Deutsch', subtitle: 'Alemão'),
    SupportedLanguageOption(
      code: 'no',
      title: 'Norsk Bokmal',
      subtitle: 'Bokmal norueguês',
    ),
    SupportedLanguageOption(
      code: 'zh',
      title: '简体中文',
      subtitle: 'Chinês simplificado',
    ),
    SupportedLanguageOption(
      code: 'zh_TW',
      title: '傳統中文',
      subtitle: 'Chinês tradicional',
    ),
    SupportedLanguageOption(code: 'ko', title: '한국인', subtitle: 'Coreano'),
    SupportedLanguageOption(code: 'hr', title: 'Hrvatski', subtitle: 'Croata'),
    SupportedLanguageOption(
      code: 'da',
      title: 'Dansk',
      subtitle: 'Dinamarquês',
    ),
    SupportedLanguageOption(
      code: 'sl',
      title: 'Slovencina',
      subtitle: 'Eslovaco',
    ),
    SupportedLanguageOption(code: 'es', title: 'Español', subtitle: 'Espanhol'),
    SupportedLanguageOption(code: 'fi', title: 'Suomi', subtitle: 'Finlandês'),
    SupportedLanguageOption(code: 'fr', title: 'Français', subtitle: 'Francês'),
  ];

  static const _textsByLanguage = <String, Map<AppTextKey, String>>{
    'pt': {
      AppTextKey.menuLanguage: 'Idioma',
      AppTextKey.menuHelpCenter: 'Centro de ajuda',
      AppTextKey.menuAboutUs: 'Sobre Nós',
      AppTextKey.menuProfile: 'Meu Perfil',
      AppTextKey.languageDone: 'Concluído',
      AppTextKey.languageCancel: 'Cancelar',
      AppTextKey.languageTitle: 'Idioma',
      AppTextKey.aboutClose: 'Fechar',
      AppTextKey.aboutTitle: 'Sobre nós',
      AppTextKey.aboutContactUs: 'Contacte-nos:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: 'Centro de ajuda',
      AppTextKey.helpCenterPlaceholder:
          'Esta seção estará disponível em breve.',
      AppTextKey.profileTitle: 'Meu Perfil',
      AppTextKey.profileLoginTab: 'Entrar',
      AppTextKey.profileRegisterTab: 'Cadastrar',
      AppTextKey.profileEmail: 'E-mail',
      AppTextKey.profileName: 'Nome',
      AppTextKey.profileLoginButton: 'Entrar',
      AppTextKey.profileRegisterButton: 'Criar conta',
      AppTextKey.profileLoginError: 'Não foi possível fazer login.',
      AppTextKey.profileRegisterError: 'Não foi possível criar a conta.',
      AppTextKey.profilePasskeyUnavailable:
          'Passkey indisponivel neste dispositivo.',
      AppTextKey.profileLoginSuccess: 'Login realizado com sucesso.',
      AppTextKey.profileRegisterSuccess: 'Conta criada com sucesso.',
        AppTextKey.profileSuccessRedirecting:
          'Logado/cadastrado com sucesso! Redirecionando...',
        AppTextKey.profileLoggedInTitle: 'Perfil autenticado',
        AppTextKey.profileDeviceFingerprintLabel: 'Nome do dispositivo',
        AppTextKey.profileLogoutButton: 'Fazer logout',
        AppTextKey.profileLogoutSuccess: 'Logout realizado com sucesso.',
        AppTextKey.profileMenuButton: 'Menu',
      AppTextKey.cameraInstruction: 'Fotografa um problema de matemática',
      AppTextKey.cameraCalculator: 'Calculadora',
      AppTextKey.cameraChatbot: 'Killbot',
        AppTextKey.cameraChatLoginRequired:
          'Faça login para acessar o Killbot.',
      AppTextKey.calculatorTitle: 'Calculadora',
      AppTextKey.calculatorClose: 'Fechar',
      AppTextKey.calculatorSolveBadRequest:
          'Equacao invalida ou nao pode ser resolvida.',
      AppTextKey.calculatorSolveError: 'Nao foi possivel resolver a equacao.',
      AppTextKey.chatTitle: 'Chat Assistant',
      AppTextKey.chatTopicLabel: 'Topico',
      AppTextKey.chatTopicHint: 'Ex: Logarithm',
      AppTextKey.chatSubmit: 'Consultar',
      AppTextKey.chatRequestMoreExample: 'Pedir mais exemplo',
      AppTextKey.chatChangeTopic: 'Trocar topico',
      AppTextKey.chatRetryTopics: 'Tentar topicos novamente',
      AppTextKey.chatEmptyResponse: 'Nenhuma resposta ainda.',
      AppTextKey.chatTopicRequired: 'Informe um topico para continuar.',
      AppTextKey.chatConsultError: 'Nao foi possivel consultar o assistente.',
    },
    'en': {
      AppTextKey.menuLanguage: 'Language',
      AppTextKey.menuHelpCenter: 'Help center',
      AppTextKey.menuAboutUs: 'About us',
      AppTextKey.menuProfile: 'My Profile',
      AppTextKey.languageDone: 'Done',
      AppTextKey.languageCancel: 'Cancel',
      AppTextKey.languageTitle: 'Language',
      AppTextKey.aboutClose: 'Close',
      AppTextKey.aboutTitle: 'About us',
      AppTextKey.aboutContactUs: 'Contact us:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - Sao Paulo - SP',
      AppTextKey.helpCenterTitle: 'Help center',
      AppTextKey.helpCenterPlaceholder: 'This section will be available soon.',
      AppTextKey.profileTitle: 'My Profile',
      AppTextKey.profileLoginTab: 'Login',
      AppTextKey.profileRegisterTab: 'Register',
      AppTextKey.profileEmail: 'E-mail',
      AppTextKey.profileName: 'Name',
      AppTextKey.profileLoginButton: 'Login',
      AppTextKey.profileRegisterButton: 'Create account',
      AppTextKey.profileLoginError: 'Could not log in.',
      AppTextKey.profileRegisterError: 'Could not create account.',
      AppTextKey.profilePasskeyUnavailable:
          'Passkey is unavailable on this device.',
      AppTextKey.profileLoginSuccess: 'Logged in successfully.',
      AppTextKey.profileRegisterSuccess: 'Account created successfully.',
        AppTextKey.profileSuccessRedirecting:
          'Logged in/registered successfully! Redirecting...',
        AppTextKey.profileLoggedInTitle: 'Authenticated profile',
        AppTextKey.profileDeviceFingerprintLabel: 'Device Name',
        AppTextKey.profileLogoutButton: 'Logout',
        AppTextKey.profileLogoutSuccess: 'Logged out successfully.',
        AppTextKey.profileMenuButton: 'Menu',
      AppTextKey.cameraInstruction: 'Take a photo of a math problem',
      AppTextKey.cameraCalculator: 'Calculator',
      AppTextKey.cameraChatbot: 'Killbot',
        AppTextKey.cameraChatLoginRequired:
          'Please log in to access Killbot.',
      AppTextKey.calculatorTitle: 'Calculator',
      AppTextKey.calculatorClose: 'Close',
      AppTextKey.calculatorSolveBadRequest:
          'Invalid equation or it could not be solved.',
      AppTextKey.calculatorSolveError: 'Could not solve the equation.',
      AppTextKey.chatTitle: 'Chat Assistant',
      AppTextKey.chatTopicLabel: 'Topic',
      AppTextKey.chatTopicHint: 'Ex: Logarithm',
      AppTextKey.chatSubmit: 'Consult',
      AppTextKey.chatRequestMoreExample: 'Ask for another example',
      AppTextKey.chatChangeTopic: 'Change topic',
      AppTextKey.chatRetryTopics: 'Retry topics',
      AppTextKey.chatEmptyResponse: 'No response yet.',
      AppTextKey.chatTopicRequired: 'Enter a topic to continue.',
      AppTextKey.chatConsultError: 'Could not reach the assistant.',
    },
    'de': {
      AppTextKey.menuLanguage: 'Sprache',
      AppTextKey.menuHelpCenter: 'Hilfecenter',
      AppTextKey.menuAboutUs: 'Über uns',
      AppTextKey.menuProfile: 'Mein Profil',
      AppTextKey.languageDone: 'Fertig',
      AppTextKey.languageCancel: 'Abbrechen',
      AppTextKey.languageTitle: 'Sprache',
      AppTextKey.aboutClose: 'Schließen',
      AppTextKey.aboutTitle: 'Über uns',
      AppTextKey.aboutContactUs: 'Kontakt:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: 'Hilfecenter',
      AppTextKey.helpCenterPlaceholder:
          'Dieser Bereich wird bald verfügbar sein.',
      AppTextKey.profileTitle: 'Mein Profil',
      AppTextKey.profileLoginTab: 'Anmelden',
      AppTextKey.profileRegisterTab: 'Registrieren',
      AppTextKey.profileEmail: 'E-Mail',
      AppTextKey.profileName: 'Name',
      AppTextKey.profileLoginButton: 'Anmelden',
      AppTextKey.profileRegisterButton: 'Konto erstellen',
      AppTextKey.profileLoginError: 'Anmeldung fehlgeschlagen.',
      AppTextKey.profileRegisterError: 'Konto konnte nicht erstellt werden.',
      AppTextKey.cameraInstruction: 'Fotografiere ein Matheproblem',
      AppTextKey.cameraCalculator: 'Rechner',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: 'Rechner',
      AppTextKey.calculatorClose: 'Schließen',
      AppTextKey.calculatorSolveError:
          'Die Gleichung konnte nicht gelöst werden.',
      AppTextKey.chatTitle: 'Chat-Assistent',
      AppTextKey.chatTopicLabel: 'Thema',
      AppTextKey.chatTopicHint: 'z.B.: Logarithmus',
      AppTextKey.chatSubmit: 'Anfragen',
      AppTextKey.chatEmptyResponse: 'Noch keine Antwort.',
      AppTextKey.chatTopicRequired: 'Bitte ein Thema eingeben.',
      AppTextKey.chatConsultError: 'Assistent nicht erreichbar.',
    },
    'no': {
      AppTextKey.menuLanguage: 'Språk',
      AppTextKey.menuHelpCenter: 'Hjelpesenter',
      AppTextKey.menuAboutUs: 'Om oss',
      AppTextKey.menuProfile: 'Min profil',
      AppTextKey.languageDone: 'Ferdig',
      AppTextKey.languageCancel: 'Avbryt',
      AppTextKey.languageTitle: 'Språk',
      AppTextKey.aboutClose: 'Lukk',
      AppTextKey.aboutTitle: 'Om oss',
      AppTextKey.aboutContactUs: 'Kontakt oss:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: 'Hjelpesenter',
      AppTextKey.helpCenterPlaceholder: 'Denne seksjonen kommer snart.',
      AppTextKey.profileTitle: 'Min profil',
      AppTextKey.profileLoginTab: 'Logg inn',
      AppTextKey.profileRegisterTab: 'Registrer',
      AppTextKey.profileEmail: 'E-post',
      AppTextKey.profileName: 'Navn',
      AppTextKey.profileLoginButton: 'Logg inn',
      AppTextKey.profileRegisterButton: 'Opprett konto',
      AppTextKey.profileLoginError: 'Kunne ikke logge inn.',
      AppTextKey.profileRegisterError: 'Kunne ikke opprette konto.',
      AppTextKey.cameraInstruction: 'Fotografer et mateproblem',
      AppTextKey.cameraCalculator: 'Kalkulator',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: 'Kalkulator',
      AppTextKey.calculatorClose: 'Lukk',
      AppTextKey.calculatorSolveError: 'Kunne ikke løse ligningen.',
      AppTextKey.chatTitle: 'Chat-assistent',
      AppTextKey.chatTopicLabel: 'Emne',
      AppTextKey.chatTopicHint: 'F.eks.: Logaritme',
      AppTextKey.chatSubmit: 'Send',
      AppTextKey.chatEmptyResponse: 'Ingen svar ennå.',
      AppTextKey.chatTopicRequired: 'Skriv inn et emne for å fortsette.',
      AppTextKey.chatConsultError: 'Kunne ikke nå assistenten.',
    },
    'zh': {
      AppTextKey.menuLanguage: '语言',
      AppTextKey.menuHelpCenter: '帮助中心',
      AppTextKey.menuAboutUs: '关于我们',
      AppTextKey.menuProfile: '我的资料',
      AppTextKey.languageDone: '完成',
      AppTextKey.languageCancel: '取消',
      AppTextKey.languageTitle: '语言',
      AppTextKey.aboutClose: '关闭',
      AppTextKey.aboutTitle: '关于我们',
      AppTextKey.aboutContactUs: '联系我们：',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: '帮助中心',
      AppTextKey.helpCenterPlaceholder: '本节即将推出。',
      AppTextKey.profileTitle: '我的资料',
      AppTextKey.profileLoginTab: '登录',
      AppTextKey.profileRegisterTab: '注册',
      AppTextKey.profileEmail: '电子邮件',
      AppTextKey.profileName: '姓名',
      AppTextKey.profileLoginButton: '登录',
      AppTextKey.profileRegisterButton: '创建账户',
      AppTextKey.profileLoginError: '无法登录。',
      AppTextKey.profileRegisterError: '无法创建账户。',
      AppTextKey.cameraInstruction: '拍摄数学题照片',
      AppTextKey.cameraCalculator: '计算器',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: '计算器',
      AppTextKey.calculatorClose: '关闭',
      AppTextKey.calculatorSolveError: '无法求解方程。',
      AppTextKey.chatTitle: '聊天助手',
      AppTextKey.chatTopicLabel: '主题',
      AppTextKey.chatTopicHint: '例：对数',
      AppTextKey.chatSubmit: '查询',
      AppTextKey.chatEmptyResponse: '暂无回复。',
      AppTextKey.chatTopicRequired: '请输入主题以继续。',
      AppTextKey.chatConsultError: '无法联系助手。',
    },
    'ko': {
      AppTextKey.menuLanguage: '언어',
      AppTextKey.menuHelpCenter: '도움말 센터',
      AppTextKey.menuAboutUs: '회사 소개',
      AppTextKey.menuProfile: '내 프로필',
      AppTextKey.languageDone: '완료',
      AppTextKey.languageCancel: '취소',
      AppTextKey.languageTitle: '언어',
      AppTextKey.aboutClose: '닫기',
      AppTextKey.aboutTitle: '회사 소개',
      AppTextKey.aboutContactUs: '문의하기:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: '도움말 센터',
      AppTextKey.helpCenterPlaceholder: '이 섹션은 곧 제공될 예정입니다.',
      AppTextKey.profileTitle: '내 프로필',
      AppTextKey.profileLoginTab: '로그인',
      AppTextKey.profileRegisterTab: '회원가입',
      AppTextKey.profileEmail: '이메일',
      AppTextKey.profileName: '이름',
      AppTextKey.profileLoginButton: '로그인',
      AppTextKey.profileRegisterButton: '계정 만들기',
      AppTextKey.profileLoginError: '로그인할 수 없습니다.',
      AppTextKey.profileRegisterError: '계정을 만들 수 없습니다.',
      AppTextKey.cameraInstruction: '수학 문제를 촬영하세요',
      AppTextKey.cameraCalculator: '계산기',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: '계산기',
      AppTextKey.calculatorClose: '닫기',
      AppTextKey.calculatorSolveError: '방정식을 풀 수 없습니다.',
      AppTextKey.chatTitle: '채팅 도우미',
      AppTextKey.chatTopicLabel: '주제',
      AppTextKey.chatTopicHint: '예: 로그',
      AppTextKey.chatSubmit: '조회',
      AppTextKey.chatEmptyResponse: '아직 응답이 없습니다.',
      AppTextKey.chatTopicRequired: '계속하려면 주제를 입력하세요.',
      AppTextKey.chatConsultError: '도우미에 연결할 수 없습니다.',
    },
    'hr': {
      AppTextKey.menuLanguage: 'Jezik',
      AppTextKey.menuHelpCenter: 'Centar za pomoć',
      AppTextKey.menuAboutUs: 'O nama',
      AppTextKey.menuProfile: 'Moj profil',
      AppTextKey.languageDone: 'Gotovo',
      AppTextKey.languageCancel: 'Odustani',
      AppTextKey.languageTitle: 'Jezik',
      AppTextKey.aboutClose: 'Zatvori',
      AppTextKey.aboutTitle: 'O nama',
      AppTextKey.aboutContactUs: 'Kontaktirajte nas:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: 'Centar za pomoć',
      AppTextKey.helpCenterPlaceholder:
          'Ovaj odjeljak uskoro će biti dostupan.',
      AppTextKey.profileTitle: 'Moj profil',
      AppTextKey.profileLoginTab: 'Prijava',
      AppTextKey.profileRegisterTab: 'Registracija',
      AppTextKey.profileEmail: 'E-pošta',
      AppTextKey.profileName: 'Ime',
      AppTextKey.profileLoginButton: 'Prijava',
      AppTextKey.profileRegisterButton: 'Stvori račun',
      AppTextKey.profileLoginError: 'Prijava nije uspjela.',
      AppTextKey.profileRegisterError: 'Račun nije moguće stvoriti.',
      AppTextKey.cameraInstruction: 'Fotografirajte matematički problem',
      AppTextKey.cameraCalculator: 'Kalkulator',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: 'Kalkulator',
      AppTextKey.calculatorClose: 'Zatvori',
      AppTextKey.calculatorSolveError: 'Jednadžba se nije mogla riješiti.',
      AppTextKey.chatTitle: 'Chat asistent',
      AppTextKey.chatTopicLabel: 'Tema',
      AppTextKey.chatTopicHint: 'Npr.: Logaritam',
      AppTextKey.chatSubmit: 'Pošalji',
      AppTextKey.chatEmptyResponse: 'Još nema odgovora.',
      AppTextKey.chatTopicRequired: 'Unesite temu za nastavak.',
      AppTextKey.chatConsultError: 'Asistent nije dostupan.',
    },
    'da': {
      AppTextKey.menuLanguage: 'Sprog',
      AppTextKey.menuHelpCenter: 'Hjælpecenter',
      AppTextKey.menuAboutUs: 'Om os',
      AppTextKey.menuProfile: 'Min profil',
      AppTextKey.languageDone: 'Færdig',
      AppTextKey.languageCancel: 'Annuller',
      AppTextKey.languageTitle: 'Sprog',
      AppTextKey.aboutClose: 'Luk',
      AppTextKey.aboutTitle: 'Om os',
      AppTextKey.aboutContactUs: 'Kontakt os:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: 'Hjælpecenter',
      AppTextKey.helpCenterPlaceholder: 'Dette afsnit kommer snart.',
      AppTextKey.profileTitle: 'Min profil',
      AppTextKey.profileLoginTab: 'Log ind',
      AppTextKey.profileRegisterTab: 'Registrer',
      AppTextKey.profileEmail: 'E-mail',
      AppTextKey.profileName: 'Navn',
      AppTextKey.profileLoginButton: 'Log ind',
      AppTextKey.profileRegisterButton: 'Opret konto',
      AppTextKey.profileLoginError: 'Kunne ikke logge ind.',
      AppTextKey.profileRegisterError: 'Konto kunne ikke oprettes.',
      AppTextKey.cameraInstruction: 'Fotografer et matematisk problem',
      AppTextKey.cameraCalculator: 'Lommeregner',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: 'Lommeregner',
      AppTextKey.calculatorClose: 'Luk',
      AppTextKey.calculatorSolveError: 'Ligningen kunne ikke løses.',
      AppTextKey.chatTitle: 'Chat-assistent',
      AppTextKey.chatTopicLabel: 'Emne',
      AppTextKey.chatTopicHint: 'F.eks.: Logaritme',
      AppTextKey.chatSubmit: 'Send',
      AppTextKey.chatEmptyResponse: 'Ingen svar endnu.',
      AppTextKey.chatTopicRequired: 'Indtast et emne for at fortsætte.',
      AppTextKey.chatConsultError: 'Kunne ikke nå assistenten.',
    },
    'sl': {
      AppTextKey.menuLanguage: 'Jazyk',
      AppTextKey.menuHelpCenter: 'Centrum pomoci',
      AppTextKey.menuAboutUs: 'O nás',
      AppTextKey.menuProfile: 'Môj profil',
      AppTextKey.languageDone: 'Hotovo',
      AppTextKey.languageCancel: 'Zrušiť',
      AppTextKey.languageTitle: 'Jazyk',
      AppTextKey.aboutClose: 'Zavrieť',
      AppTextKey.aboutTitle: 'O nás',
      AppTextKey.aboutContactUs: 'Kontaktujte nás:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: 'Centrum pomoci',
      AppTextKey.helpCenterPlaceholder:
          'Táto sekcia bude čoskoro k dispozícii.',
      AppTextKey.profileTitle: 'Môj profil',
      AppTextKey.profileLoginTab: 'Prihlásiť sa',
      AppTextKey.profileRegisterTab: 'Registrovať',
      AppTextKey.profileEmail: 'E-mail',
      AppTextKey.profileName: 'Meno',
      AppTextKey.profileLoginButton: 'Prihlásiť sa',
      AppTextKey.profileRegisterButton: 'Vytvoriť účet',
      AppTextKey.profileLoginError: 'Prihlásenie sa nepodarilo.',
      AppTextKey.profileRegisterError: 'Účet sa nepodarilo vytvoriť.',
      AppTextKey.cameraInstruction: 'Odfotografujte matematický problém',
      AppTextKey.cameraCalculator: 'Kalkulačka',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: 'Kalkulačka',
      AppTextKey.calculatorClose: 'Zavrieť',
      AppTextKey.calculatorSolveError: 'Rovnicu sa nepodarilo vyriešiť.',
      AppTextKey.chatTitle: 'Chat asistent',
      AppTextKey.chatTopicLabel: 'Téma',
      AppTextKey.chatTopicHint: 'Napr.: Logaritmus',
      AppTextKey.chatSubmit: 'Odoslať',
      AppTextKey.chatEmptyResponse: 'Zatiaľ žiadna odpoveď.',
      AppTextKey.chatTopicRequired: 'Zadajte tému pre pokračovanie.',
      AppTextKey.chatConsultError: 'Asistenta sa nepodarilo dosiahnuť.',
    },
    'es': {
      AppTextKey.menuLanguage: 'Idioma',
      AppTextKey.menuHelpCenter: 'Centro de ayuda',
      AppTextKey.menuAboutUs: 'Sobre nosotros',
      AppTextKey.menuProfile: 'Mi perfil',
      AppTextKey.languageDone: 'Listo',
      AppTextKey.languageCancel: 'Cancelar',
      AppTextKey.languageTitle: 'Idioma',
      AppTextKey.aboutClose: 'Cerrar',
      AppTextKey.aboutTitle: 'Sobre nosotros',
      AppTextKey.aboutContactUs: 'Contáctenos:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: 'Centro de ayuda',
      AppTextKey.helpCenterPlaceholder:
          'Esta sección estará disponible pronto.',
      AppTextKey.profileTitle: 'Mi perfil',
      AppTextKey.profileLoginTab: 'Iniciar sesión',
      AppTextKey.profileRegisterTab: 'Registrarse',
      AppTextKey.profileEmail: 'Correo electrónico',
      AppTextKey.profileName: 'Nombre',
      AppTextKey.profileLoginButton: 'Iniciar sesión',
      AppTextKey.profileRegisterButton: 'Crear cuenta',
      AppTextKey.profileLoginError: 'No se pudo iniciar sesión.',
      AppTextKey.profileRegisterError: 'No se pudo crear la cuenta.',
      AppTextKey.cameraInstruction: 'Fotografía un problema de matemáticas',
      AppTextKey.cameraCalculator: 'Calculadora',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: 'Calculadora',
      AppTextKey.calculatorClose: 'Cerrar',
      AppTextKey.calculatorSolveError: 'No se pudo resolver la ecuación.',
      AppTextKey.chatTitle: 'Asistente de chat',
      AppTextKey.chatTopicLabel: 'Tema',
      AppTextKey.chatTopicHint: 'Ej.: Logaritmo',
      AppTextKey.chatSubmit: 'Consultar',
      AppTextKey.chatEmptyResponse: 'Sin respuesta aún.',
      AppTextKey.chatTopicRequired: 'Ingresa un tema para continuar.',
      AppTextKey.chatConsultError: 'No se pudo contactar al asistente.',
    },
    'fi': {
      AppTextKey.menuLanguage: 'Kieli',
      AppTextKey.menuHelpCenter: 'Tukikeskus',
      AppTextKey.menuAboutUs: 'Tietoja meistä',
      AppTextKey.menuProfile: 'Oma profiili',
      AppTextKey.languageDone: 'Valmis',
      AppTextKey.languageCancel: 'Peruuta',
      AppTextKey.languageTitle: 'Kieli',
      AppTextKey.aboutClose: 'Sulje',
      AppTextKey.aboutTitle: 'Tietoja meistä',
      AppTextKey.aboutContactUs: 'Ota yhteyttä:',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: 'Tukikeskus',
      AppTextKey.helpCenterPlaceholder: 'Tämä osio on pian saatavilla.',
      AppTextKey.profileTitle: 'Oma profiili',
      AppTextKey.profileLoginTab: 'Kirjaudu',
      AppTextKey.profileRegisterTab: 'Rekisteröidy',
      AppTextKey.profileEmail: 'Sähköposti',
      AppTextKey.profileName: 'Nimi',
      AppTextKey.profileLoginButton: 'Kirjaudu',
      AppTextKey.profileRegisterButton: 'Luo tili',
      AppTextKey.profileLoginError: 'Kirjautuminen epäonnistui.',
      AppTextKey.profileRegisterError: 'Tilin luominen epäonnistui.',
      AppTextKey.cameraInstruction: 'Kuvaa matemaattinen ongelma',
      AppTextKey.cameraCalculator: 'Laskin',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: 'Laskin',
      AppTextKey.calculatorClose: 'Sulje',
      AppTextKey.calculatorSolveError: 'Yhtälöä ei voitu ratkaista.',
      AppTextKey.chatTitle: 'Chat-assistentti',
      AppTextKey.chatTopicLabel: 'Aihe',
      AppTextKey.chatTopicHint: 'Esim.: Logaritmi',
      AppTextKey.chatSubmit: 'Lähetä',
      AppTextKey.chatEmptyResponse: 'Ei vastausta vielä.',
      AppTextKey.chatTopicRequired: 'Syötä aihe jatkaaksesi.',
      AppTextKey.chatConsultError: 'Assistenttia ei voitu tavoittaa.',
    },
    'fr': {
      AppTextKey.menuLanguage: 'Langue',
      AppTextKey.menuHelpCenter: "Centre d'aide",
      AppTextKey.menuAboutUs: 'À propos',
      AppTextKey.menuProfile: 'Mon profil',
      AppTextKey.languageDone: 'Terminé',
      AppTextKey.languageCancel: 'Annuler',
      AppTextKey.languageTitle: 'Langue',
      AppTextKey.aboutClose: 'Fermer',
      AppTextKey.aboutTitle: 'À propos',
      AppTextKey.aboutContactUs: 'Contactez-nous :',
      AppTextKey.aboutEmail: 'Suporte pelo aplicativo',
      AppTextKey.aboutAddress: 'Av. Dr. Adolpho Pinto, 109 - São Paulo - SP',
      AppTextKey.helpCenterTitle: "Centre d'aide",
      AppTextKey.helpCenterPlaceholder:
          'Cette section sera bientôt disponible.',
      AppTextKey.profileTitle: 'Mon profil',
      AppTextKey.profileLoginTab: 'Connexion',
      AppTextKey.profileRegisterTab: "S'inscrire",
      AppTextKey.profileEmail: 'E-mail',
      AppTextKey.profileName: 'Nom',
      AppTextKey.profileLoginButton: 'Connexion',
      AppTextKey.profileRegisterButton: 'Créer un compte',
      AppTextKey.profileLoginError: 'Connexion impossible.',
      AppTextKey.profileRegisterError: 'Impossible de créer le compte.',
      AppTextKey.cameraInstruction: 'Prenez en photo un problème de maths',
      AppTextKey.cameraCalculator: 'Calculatrice',
      AppTextKey.cameraChatbot: 'Killbot',
      AppTextKey.calculatorTitle: 'Calculatrice',
      AppTextKey.calculatorClose: 'Fermer',
      AppTextKey.calculatorSolveError: "L'équation n'a pas pu être résolue.",
      AppTextKey.chatTitle: 'Assistant de chat',
      AppTextKey.chatTopicLabel: 'Sujet',
      AppTextKey.chatTopicHint: 'Ex : Logarithme',
      AppTextKey.chatSubmit: 'Consulter',
      AppTextKey.chatEmptyResponse: 'Pas encore de réponse.',
      AppTextKey.chatTopicRequired: 'Saisissez un sujet pour continuer.',
      AppTextKey.chatConsultError: "Impossible de joindre l'assistant.",
    },
  };

  String text({required AppTextKey key, required String languageCode}) {
    final normalizedCode = _normalize(languageCode);
    final selected =
        _textsByLanguage[normalizedCode] ??
        _textsByLanguage[fallbackLanguageCode]!;
    return selected[key] ?? _textsByLanguage[fallbackLanguageCode]![key]!;
  }

  String languageNameForMenu(String languageCode) {
    final normalizedCode = _normalize(languageCode);
    final option = supportedLanguageOptions.firstWhere(
      (item) => item.code == normalizedCode,
      orElse: () => supportedLanguageOptions.first,
    );
    return option.title;
  }

  static String _normalize(String languageCode) {
    final first = languageCode.split('_').first;
    return first.toLowerCase();
  }
}
